### ISSUE TITLE
Неверный список участников голосового канала при выходе из сервера

### ISSUE THREAD

**Issue by AymanDev** [AymanDev/YuiBot#1]
Если выйти с сервера и не выйти изначально из голосового канала, то discord.js выдает неверный список, содержащий в себе этого пользователя.

**Comment by AymanDev** [comment]
Исправлено путем фильтрования списка, проверяя, что этот пользователь является участником сервера, если нет, то исключать из списка.

**Comment by RashkaByorn** [comment]
Баг с вышедшем пользователем

Баг опять проявился. Данный пользователь не находится на сервере вообще. Не знаю когда он вышел с сервера, толи во время поиска, только после. Но он опять был 5ым в списке.
![BUG](https://trello-attachments.s3.amazonaws.com/5bc1e7fa12da0b0d7edde1cd/5bc8d5223ce7e36c83ac4d0f/bcaffe39ee5e1fbac94c3506684f4c4a/2018-10-18_22-27-06.png)

**Comment by AymanDev** [comment]
Исправлено из-за недочета во время фильтрования списка. После фильтрования шла итерация через список, но отфильтрованный список не присваивался к списку для итерации.
